ALTER TABLE "Hotel" ADD COLUMN "commissionPercent" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Hotel" ADD COLUMN "availableRooms" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Hotel" ADD COLUMN "maxGuestsPerRoom" INTEGER NOT NULL DEFAULT 2;

ALTER TABLE "Booking" ADD COLUMN "roomsCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Booking" ADD COLUMN "commissionPercent" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN "commissionAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
